import Head from "next/head";
import Image from "next/image";
import NavBar from "../component/NavBar/NavBar";
import HomeScreen from "../component/Home/HomeScreen";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Space Tourism website by Joseph Kabemba</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <HomeScreen />
      <main></main>
    </div>
  );
}
